// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcHUAUDmP2ZB2XV9FB2W7bsoRlp9fAM3A',
    appId: '1:1074242601194:web:0572a4df7c8c5bad7dd793',
    messagingSenderId: '1074242601194',
    projectId: 'roadcare-2d68d',
    authDomain: 'roadcare-2d68d.firebaseapp.com',
    storageBucket: 'roadcare-2d68d.firebasestorage.app',
    measurementId: 'G-X2S4BZFNJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxwZhWzJhFYnhHGkHEaZhCz_yQd7ytJaI',
    appId: '1:1074242601194:android:5ee47d89061187f07dd793',
    messagingSenderId: '1074242601194',
    projectId: 'roadcare-2d68d',
    storageBucket: 'roadcare-2d68d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjjbcXxZub3KEwgT7nZd6oFPpWIhqczRI',
    appId: '1:1074242601194:ios:662d3c6c17bc35387dd793',
    messagingSenderId: '1074242601194',
    projectId: 'roadcare-2d68d',
    storageBucket: 'roadcare-2d68d.firebasestorage.app',
    iosBundleId: 'com.example.roadcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjjbcXxZub3KEwgT7nZd6oFPpWIhqczRI',
    appId: '1:1074242601194:ios:662d3c6c17bc35387dd793',
    messagingSenderId: '1074242601194',
    projectId: 'roadcare-2d68d',
    storageBucket: 'roadcare-2d68d.firebasestorage.app',
    iosBundleId: 'com.example.roadcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcHUAUDmP2ZB2XV9FB2W7bsoRlp9fAM3A',
    appId: '1:1074242601194:web:2414438954ae3b7a7dd793',
    messagingSenderId: '1074242601194',
    projectId: 'roadcare-2d68d',
    authDomain: 'roadcare-2d68d.firebaseapp.com',
    storageBucket: 'roadcare-2d68d.firebasestorage.app',
    measurementId: 'G-J6L3JZMMPZ',
  );
}
